# Time Independent Perturbation Theory 
## Introduction 

Suppose we successfully solved for the eigensystem 
$\{E_n^0, \psi_n^0\}$ for a time-independent Hamiltonian \(H^0\). 
Perturbation theory approximates the eigensystem for the perturbed Hamiltonian 
\[
H = H^0 + \lambda H'
\]

The key assumption of perturbation theory is that 
_the eigensystem has a power series expansion in terms of \(\lambda\)_. 
We use this assumption and the known solutions for \(\lambda=0\) 
to solve for the perturbed eigensystem at \(\lambda=1\). Concretely,
\[
\begin{align}
    \psi_n &= \psi_n^0 + \lambda \psi_n^1 + \lambda^2 \psi_n^2 + \cdots \\ 
    E_n &= E_n^0 + \lambda E_n^1 + \lambda^2 E_n^2 + \cdots 
\end{align}
\]
The subscript denotes the eigensystem index and superscript correction order. 
Substitute into the eigenvalue equation for \(H\) to yield 
\[
(H^0 + \lambda H')(\psi_n^0 + \lambda \psi_n^1 + \cdots) = (E_n^0 + \lambda E_n^1 + \cdots)(\psi_n^0 + \lambda \psi_n^1 + \cdots)
\]
By assumption, this equation holds independently for every power of \(\lambda\). 
In the zeroth order 
\[
H^0\psi_n^0 = E_n^0 \psi_n^0
\]
To the first and second orders 

\begin{equation}
\begin{aligned}
    H^0\psi_n^1 + H'\psi_n^0 &= E_n^0\psi_n^1 + E_n^1\psi_n^0 \\ 
    H^0\psi_n^2 + H'\psi_n^1 &= E_n^0 \psi_n^2 + E_n^1\psi_n^1 + E_n^2 \psi_n^0
\end{aligned}
(\#eq:independentFirstSecondPerturbation)
\end{equation}

::: {.remark}
The power series expansion assumption of perturbation theory is not generally true. 
The solutions to a physical system are usually not smooth around \(\lambda=0\), 
as positive and negative coupling may lead to qualitatively different behaviors 
(consider a two-body system with attractive compared to repulsive interaction). 
This manifests mathematically in the divergence of higher-order terms. 
It is quite a miracle that we can use the first few terms in the perturbation 
series with a good conscience in the first place. 
:::


## Nondegenerate Theory 
Take the inner product of the first equation in 
\@ref(eq:independentFirstSecondPerturbation) 
with \(\psi_n^0\) to isolate a component
\[
\la \psi_n^0|H^0|\psi_n^1\ra + \la \psi_n^0|H'|\psi_n^0\ra 
= E_n^0\la \psi_n^0|\psi_n^1\ra + E_n^1\la \psi_n^0|\psi_n^0\ra
\]
The Hamiltonian \(H^0\) is Hermitian, 
so the first terms on both sides of the equation cancel. 
The first-order energy correction is a matrix element of 
\(H'\) in the orthonormal basis \(\{|\psi_n^0\ra\}\).
\[
E_n^1 = \la \psi_n^0|H'|\psi_n^0\ra
\]
For the first order eigenstate correction, 
rewrite equation \@ref(eq:independentFirstSecondPerturbation) 
as an equation in \(\psi_n^1\).
\[
(H^0 - E_n^0)\psi_n^1 = -(H' - E_n^1)\psi_n^0
\]
Any solution has freedom under 
\(\psi_n^1\mapsto \psi_n^1 + \alpha \psi_n^0\), since this is in the 
kernel of the left-hand-side operator $(H^0 - E_n^0)$. 
Expand \(\psi_n^1\) in the orthonormal basis
\[
\psi_n^1 = \sum_{m\neq n} c_m^{(n)} \psi_m^0 
(\#eq:perturbationExpansion)
\]
Without loss of generality we may assume the $\psi_n^0$ component to be 
zero. Substitute into the equation
\[
\sum_{m\neq n}\left(E_m^0 - E_n^0\right)c_m^{(n)}\psi_m^0 = -(H' - E_n^1)\psi_n^0
\]
Again, to isolate components, take the inner product with \(\psi_l^0\) for \(l\neq n\)
\[
\left(E_l^0 - E_n^0\right)c_l^{(n)} = -\la \psi_l^0|H'|\psi_n^0\ra
\]
Solve for \(c_l^{(n)}\) and substitute into \@ref(eq:perturbationExpansion), 
yielding the first-order eigenfunction corrections
\[
|\psi_n^1\ra = \sum_{m\neq n} \df{\ang{\psi_m^0|H'|\psi_n^0}}{E_n^0 - E_m^0}|\psi_m^0\ra
\]
For \(E_n^2\), consider the second equation in 
\@ref(eq:independentFirstSecondPerturbation). 
Inner product with \(\psi_n^0\) to isolate components
\[
\la \psi_n^0|H^0|\psi_n^2\ra + \la \psi_n^0|H'|\psi_n^1\ra = E_n^0 \la \psi_n^0|\psi_n^2\ra + E_n^1\la \psi_n^0|\psi_n^1\ra + E_n^2\la \psi_n^0|\psi_n^0\ra
\]
Again, the first term on both sides cancel, so
\[
E_n^2 = \la \psi_n^0|H'|\psi_n^1\ra - E_n^1\la \psi_n^0|\psi_n^1\ra
\]
Recall that we excluded \(\psi_n^0\) in the expansion for \(|\psi_n^1\ra\) 
in \@ref(eq:perturbationExpansion) so \(\la \psi_n^0|\psi_n^1\ra = 0\), 
then putting our results in one place:
Recall that we excluded \(\psi_n^0\) in the expansion for \(|\psi_n^1\ra\) 
in \@ref(eq:perturbationExpansion) so \(\la \psi_n^0|\psi_n^1\ra = 0\), 
then putting our results in one place:
\[
\begin{aligned}
    E_n^1 &= \la \psi_n^0|H'|\psi_n^0\ra \\ 
    |\psi_n^1\ra &= \sum_{m\neq n} \df{\ang{\psi_m^0|H'|\psi_n^0}}{E_n^0 - E_m^0}|\psi_m^0\ra \\
    E_n^2 &= \sum_{m\neq n} \df{|\la \psi_m^0|H'|\psi_n^0\ra|^2}{E_n^0 - E_m^0}
\end{aligned}
(\#eq:perturbationResults)
\]


## Degenerate Theory

In the case of degeneracy, we need to think more rigorously about our solutions:

The zeroth order equation \(H^0 \psi_n^0 = E_n^0 \psi_n^0\) 
becomes under-determined: when the eigenspace \(E_n^0\) is of 
dimension greater than 1, there are many eigenstates which 
satisfy the zeroth-order. 
This problem asserts itself when we consider the 
first-order eigenstate correction 

\[
|\psi_n^{1}\rangle = \sum_{m \neq n} 
\frac{\langle \psi_m^0 | H' | \psi_n^0 \rangle}
{E_n^0 - E_m^0} | \psi_m^0 \rangle
\]

This is not defined in case of degeneracy, 
when \(E_n^0 = E_m^0\) for some \(n \neq m\). 
The same holds for the second order energy correction. 

One way to make sense of the first-order eigenfunction 
correction equation is to choose a "good" basis for the degenerate eigenspace such that 
\[
\forall n\neq m, E_n^0 = E_m^0 \implies \langle \psi_m^0 | H' | \psi_n^0 \rangle = 0
\]
This allows us to cancel the zero denominators in \@ref(eq:perturbationResults) with a zero enumerator and hope that no higher-order degeneracy exists so the indeterminate form is \(0\). We need the following definition to make precise what we mean by finding a "good" eigenbasis for \(H^0\) with respect to a perturbation \(H'\).

::: {#defSubspaceProjection .definition name="subspace projection of an operator"}
The projection of an operator \(H : V \to V\) onto a subspace \(W \subset V\) \(H_{|W} : W \to W\) is
\[
H_{|W} : W \xrightarrow{\iota} V \xrightarrow{H} V \xrightarrow{P_{V \to W}} W
\]
Given an orthonormal basis \(\{|i\ra\}\) for \(W\),
 the matrix representation of \(H_{|W}\) is just \(W_{ij} = \langle i | H | j \rangle\).
:::


::: {.definition name="good basis for perturbation"}
\(\mathcal{B} = \{|i\rangle\}\) is a "good" basis for perturbing \(H^0\) with respect to \(H'\) if, 
for every eigenspace \(W \subset V\) of \(H^0\) with basis 
\(\mathcal{A} \subseteq \mathcal{B}\), 
the representation of \(H'_{|W}\) under \(\mathcal{A}\) is diagonal. In other words,

\[
\forall |m\ra, |n\ra \in \mathcal{A}, m \neq n: H'_{mn} = 0
\]
:::

::: {.remark}
Finding a good basis is weaker than finding a simultaneous eigenbasis for \(H^0, H'\), which does not exist when \([H^0, H'] \neq 0\). A good basis \textit{always} exists by applying the spectral theorem to the projection of \(H'\) on each eigenspace of \(H^0\).
:::

::: {.theorem name="characterization of commutativity"}
Two normal operators \(A, B\) commute if and only if 
they leave the eigenspaces of each other invariant.

**Proof:** Assume commutativity, 
and let \(x\) be an eigenvector of \(A\) with eigenvalue \(\lambda\), 
then \(BAx = \lambda Bx = A(Bx)\), so \(Bx\) is also an eigenvector of \(A\) 
with eigenvalue \(\lambda\). 
Conversely, let \(x_i\) be an eigenbasis for \(A\) 
such that \(Ax_i = \lambda_i x_i, ABx_i = \lambda_i Bx_i\). 
Given an arbitrary vector \(v = c_i x_i\), we have
\[
BAv = c_i BAx_i = c_i \lambda_i Bx_i = c_i ABx_i = ABv
\]
:::

This applies in particular to two Hermitian operators. 
In a subspace spanned by eigenvectors of \(A\) with _distinct eigenvalues_, 
commutativity forces \(H\) to be diagonal.

::: {.lemma}
Given commuting Hermitian operators \(H\) and \(A\), 
\(H_{|W}\) is diagonal for every subspace \(W\) spanned by an orthonormal 
set of eigenvectors of \(A\) with distinct eigenvalues.

**Proof:** 
By \(AH = HA\), \(\la i|H|j\ra = \lambda_j^{-1}\la i|AH|j\ra = \lambda_i^{-1}\la i|HA|j\ra\). 
Since \(\lambda_i \neq \lambda_j\), \(\la i|H|j\ra = 0\).
:::

Note that commutativity is not transitive: 
\([A, H^0] = [A, H']=0\) does not imply \([H^0, H']=0\).
A trivial example: identity commutes with every normal operator, but they don't 
commute with each other. Commutativity does become transitive when all operators 
in question are not degenerate. 

::: {.theorem name="convenient good basis condition"}
Given Hermitian \(H^0, H'\). An eigenbasis \(\{|i\ra\}\) for \(H^0\) 
is a good basis if it diagonalizes an operator \(A\) such that 
\([A, H^0] = [A, H']=0\) and each subset of \(\{|i\ra\}\) 
corresponding to a degenerate subspace of \(H^0\) are eigenvectors 
of \(A\) with distinct eigenvalues.

**Proof:** Given such an \(A\) and mutual eigenbasis \(\{|i\ra\}\) between \(A, H^0\), consider each degenerate eigenspace \(W\) of \(H^0\). By the lemma above, \(H'_{|W}\) must be diagonal in this basis.
:::